#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-mocha
Version  : 1.2.1
Release  : 8
URL      : https://rubygems.org/downloads/mocha-1.2.1.gem
Source0  : https://rubygems.org/downloads/mocha-1.2.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-redcarpet
BuildRequires : rubygem-test-unit
BuildRequires : rubygem-yard

%description
## Mocha [![build status](https://secure.travis-ci.org/freerange/mocha.png)](https://secure.travis-ci.org/freerange/mocha) [![Gem Version](https://badge.fury.io/rb/mocha.png)](http://badge.fury.io/rb/mocha) [![OpenCollective](https://opencollective.com/mocha/backers/badge.svg)](#backers) [![OpenCollective](https://opencollective.com/mocha/sponsors/badge.svg)](#sponsors)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n mocha-1.2.1
gem spec %{SOURCE0} -l --ruby > rubygem-mocha.gemspec

%build
export LANG=C
gem build rubygem-mocha.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
mocha-1.2.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/mocha-1.2.1
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/mocha-1.2.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/.gemtest
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/COPYING.md
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/MIT-LICENSE.md
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/RELEASE.md
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/bin/build-matrix
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.minitest.1.3.0
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.minitest.1.4.0
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.minitest.1.4.1
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.minitest.1.4.2
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.minitest.2.0.0
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.minitest.2.0.1
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.minitest.2.11.0
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.minitest.2.11.2
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.minitest.2.3.0
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.minitest.latest
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.test-unit.2.0.0
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.test-unit.2.0.1
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.test-unit.2.0.3
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/gemfiles/Gemfile.test-unit.latest
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/init.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/any_instance_method.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/api.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/argument_iterator.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/backtrace_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/cardinality.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/central.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/change_state_side_effect.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/class_method.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/class_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/debug.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/deprecation.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/detection/mini_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/detection/test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/exception_raiser.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/expectation.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/expectation_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/expectation_error_factory.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/expectation_list.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/hooks.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/in_state_ordering_constraint.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/inspect.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/instance_method.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/assertion_counter.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/mini_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/mini_test/adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/mini_test/exception_translation.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/mini_test/nothing.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/mini_test/version_13.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/mini_test/version_140.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/mini_test/version_141.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/mini_test/version_142_to_172.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/mini_test/version_200.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/mini_test/version_201_to_222.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/mini_test/version_2110_to_2111.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/mini_test/version_2112_to_320.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/mini_test/version_230_to_2101.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/monkey_patcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/test_unit/adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/test_unit/gem_version_200.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/test_unit/gem_version_201_to_202.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/test_unit/gem_version_203_to_220.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/test_unit/gem_version_230_to_250.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/test_unit/nothing.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/test_unit/ruby_version_185_and_below.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/integration/test_unit/ruby_version_186_and_above.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/is_a.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/logger.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/method_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/mini_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/mock.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/mockery.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/module_method.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/module_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/multiple_yields.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/names.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/no_yields.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/object_methods.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/all_of.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/any_of.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/any_parameters.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/anything.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/equals.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/has_entries.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/has_entry.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/has_key.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/has_value.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/includes.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/instance_of.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/is_a.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/kind_of.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/not.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/optionally.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/query_string.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/regexp_matches.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/responds_with.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameter_matchers/yaml_equivalent.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/parameters_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/pretty_parameters.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/receivers.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/return_values.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/ruby_version.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/sequence.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/setup.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/single_return_value.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/single_yield.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/standalone.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/state_machine.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/stubbing_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/test_unit.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/thrower.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/unexpected_invocation.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha/yield_parameters.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/lib/mocha_standalone.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/mocha.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/acceptance_test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/bug_18914_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/bug_21465_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/bug_21563_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/exception_rescue_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/expectations_on_multiple_methods_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/expected_invocation_count_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/failure_messages_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/issue_272_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/issue_65_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/issue_70_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/mocha_example_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/mocha_test_result_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/mock_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/mock_with_initializer_block_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/mocked_methods_dispatch_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/multiple_expectations_failure_message_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/optional_parameters_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/parameter_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/partial_mocks_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/prepend_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/raise_exception_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/return_value_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/sequence_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/states_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_any_instance_method_defined_on_superclass_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_any_instance_method_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_class_method_defined_on_active_record_association_proxy_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_class_method_defined_on_class_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_class_method_defined_on_module_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_class_method_defined_on_superclass_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_everything_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_instance_method_defined_on_active_record_association_proxy_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_instance_method_defined_on_class_and_aliased_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_instance_method_defined_on_class_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_instance_method_defined_on_kernel_module_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_instance_method_defined_on_module_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_instance_method_defined_on_object_class_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_instance_method_defined_on_singleton_class_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_instance_method_defined_on_superclass_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_method_defined_on_module_and_aliased_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_module_method_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stub_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubba_example_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubba_test_result_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubbing_error_backtrace_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubbing_frozen_object_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubbing_method_accepting_block_parameter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubbing_method_unnecessarily_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubbing_nil_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubbing_non_existent_any_instance_method_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubbing_non_existent_class_method_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubbing_non_existent_instance_method_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubbing_non_public_any_instance_method_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubbing_non_public_class_method_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubbing_non_public_instance_method_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubbing_on_non_mock_object_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/stubbing_same_class_method_on_parent_and_child_classes_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/throw_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/unexpected_invocation_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/acceptance/unstubbing_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/assertions.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/deprecation_disabler.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/execution_point.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/integration/mini_test_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/integration/shared_tests.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/integration/test_unit_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/method_definer.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/mini_test_result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/minitest_result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/simple_counter.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/test_runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/test_unit_result.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/any_instance_method_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/array_inspect_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/backtrace_filter_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/cardinality_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/central_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/change_state_side_effect_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/class_method_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/class_methods_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/configuration_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/date_time_inspect_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/exception_raiser_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/expectation_list_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/expectation_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/hash_inspect_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/hooks_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/in_state_ordering_constraint_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/method_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/mock_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/mockery_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/module_methods_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/multiple_yields_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/no_yields_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/object_inspect_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/object_methods_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/all_of_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/any_of_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/anything_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/equals_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/has_entries_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/has_entry_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/has_key_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/has_value_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/includes_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/instance_of_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/is_a_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/kind_of_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/not_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/regexp_matches_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/responds_with_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/stub_matcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameter_matchers/yaml_equivalent_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/parameters_matcher_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/receivers_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/return_values_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/sequence_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/single_return_value_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/single_yield_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/state_machine_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/string_inspect_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/thrower_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/test/unit/yield_parameters_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/yard-templates/default/layout/html/google_analytics.erb
/usr/lib64/ruby/gems/2.3.0/gems/mocha-1.2.1/yard-templates/default/layout/html/setup.rb
/usr/lib64/ruby/gems/2.3.0/specifications/mocha-1.2.1.gemspec
